name: Mirror main branch to public repo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Force mirror the repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add public https://misantamaria:${{ secrets.GH_TOKEN }}@github.com/misantamaria/upm_pfp_mdl_dltemp.git
          
          # Traer la última versión desde el repositorio remoto
          git fetch origin
          
          # Asegurarse de que la rama main esté actualizada
          git reset --hard origin/main  # Esto asegura que todo se sobrescriba con la rama main del remoto
          
          # Verificar que esté todo en orden (esto puede ayudar a ver qué cambios se trajeron)
          git status
          
          # Forzar el push al repositorio público con la última versión de main
          git push public main --force
    permissions:
      contents: write
