name: Mirror main branch to public repo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Force mirror the repo
        run: |
          echo "Configurando Git..."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          echo "Agregando remote 'public'..."
          git remote add public https://misantamaria:${{ secrets.GH_TOKEN }}@github.com/misantamaria/upm_pfp_mdl_dltemp.git
          
          echo "Agregando remote 'private'..."
          git remote add private https://misantamaria:${{ secrets.GH_TOKEN }}@github.com/misantamaria/dltemp.git
          
          echo "Listando remotes para verificación:"
          git remote -v
          
          echo "Obteniendo la última versión de 'private/main'..."
          git fetch private
          
          echo "Reseteando el repositorio a 'private/main'..."
          git reset --hard private/main
          
          echo "Estado del repositorio tras el reset:"
          git status
          
          echo "Forzando push a 'public/main'..."
          git push public main --force
